"""Regression tests for reviewed Contextual Orchestrator evidence trust boundaries."""

from __future__ import annotations

from dataclasses import replace
from inspect import signature

import pytest

from orgmetra_contextual_orchestrator_adapter import DraftEvidenceEnvelope
from test_envelope import build, values


def test_rejects_human_readable_actor_correlation() -> None:
    """Keep durable actor evidence opaque instead of preserving human-readable handles."""
    kwargs = values()
    kwargs["requesting_actor_reference"] = "actor:Jane-Doe"
    with pytest.raises(ValueError, match="requesting_actor_reference"):
        DraftEvidenceEnvelope(**kwargs)


def test_system_recorded_time_is_not_a_caller_constructor_argument() -> None:
    """Require system-recorded time to be generated by the issuance boundary itself."""
    assert "recorded_at" not in signature(DraftEvidenceEnvelope).parameters


def test_internal_integrity_state_is_not_constructor_visible() -> None:
    """Prevent dataclass replacement from replaying caller-visible issuance internals."""
    parameters = signature(DraftEvidenceEnvelope).parameters
    assert "_creation_seal" not in parameters
    assert "_issuance_marker" not in parameters


def test_replacement_is_a_new_system_recorded_evidence_issuance() -> None:
    """Make replacement visibly new evidence rather than a rewrite of an issued envelope."""
    original = build()
    replacement = replace(original, response_evidence_digest="d" * 64)
    assert replacement.draft_evidence_reference != original.draft_evidence_reference
    assert replacement.recorded_at >= original.recorded_at
    assert replacement.evidence_digest() != original.evidence_digest()
