#!/usr/bin/env bash
# shellcheck disable=SC2153 # REVIEW*_DIGEST variables are generated by the exact fixture generator below.
set -euo pipefail

: "${DATABASE_URL:=postgresql://orgmetra:orgmetra@localhost:5432/orgmetra}"

for migration in \
  database/migrations/0001_foundation_schema.sql \
  database/migrations/0002_sealed_evidence_digest.sql \
  database/migrations/0031_employment_work_capacity_persistence.sql \
  database/migrations/0032_employment_work_capacity_forward_chain.sql; do
  if [[ ! -f "${migration}" ]]; then
    echo "required Employment work-capacity persistence migration is missing: ${migration}" >&2
    exit 1
  fi
  psql "${DATABASE_URL}" -v ON_ERROR_STOP=1 -f "${migration}"
done

unhardened_functions="$(psql "${DATABASE_URL}" -Atqc "
SELECT count(*)
FROM pg_proc
WHERE pronamespace = 'public'::regnamespace
  AND proname = ANY (ARRAY[
    'enforce_employment_work_capacity_anchor_system_time',
    'resolve_employment_work_capacity',
    'validate_employment_work_capacity_version_insert',
    'apply_employment_work_capacity_change',
    'protect_employment_work_capacity_anchor_immutability',
    'protect_employment_work_capacity_version_history',
    'reject_employment_work_capacity_truncate',
    'enforce_employment_work_capacity_forward_chain'
  ])
  AND NOT COALESCE(
    proconfig @> ARRAY['search_path=pg_catalog, public, pg_temp']::text[],
    false
  );")"
if [[ "${unhardened_functions}" != "0" ]]; then
  echo "work-capacity functions inherit caller-controlled search_path: ${unhardened_functions}" >&2
  exit 1
fi

TENANT_ID="10000000-0000-7000-8000-000000000001"
OTHER_TENANT_ID="20000000-0000-7000-8000-000000000002"
PERSON_ID="10000000-0000-7000-8000-000000000011"
EMPLOYMENT_ID="10000000-0000-7000-8000-000000000021"
EMPLOYMENT_VERSION_ID="10000000-0000-7000-8000-000000000022"
CAPACITY_RECORD_ID="10000000-0000-7000-8000-000000000031"
CAPACITY_VERSION_1="10000000-0000-7000-8000-000000000032"
CAPACITY_VERSION_2="10000000-0000-7000-8000-000000000033"
CAPACITY_VERSION_BAD="10000000-0000-7000-8000-000000000034"
REQUESTER="actor:00000000-0000-4000-8000-000000000041"
REVIEWER="actor:00000000-0000-4000-8000-000000000042"
APPLIER="actor:00000000-0000-4000-8000-000000000043"
REVIEW_AUDIT="audit_event:00000000-0000-4000-8000-000000000051"
APPLICATION_AUDIT_1="audit_event:00000000-0000-4000-8000-000000000052"
APPLICATION_AUDIT_2="audit_event:00000000-0000-4000-8000-000000000053"
APPLICATION_OUTBOX_1="outbox_event:00000000-0000-4000-8000-000000000061"
APPLICATION_OUTBOX_2="outbox_event:00000000-0000-4000-8000-000000000062"
TERMS_DIGEST="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
POLICY_DIGEST="bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
REVIEWER_DIGEST="cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
REVIEW_AUDIT_DIGEST="dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
APPLICATION_DIGEST_1="eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
APPLICATION_DIGEST_2="ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"

with_tenant() {
  local tenant="$1"
  shift
  PGOPTIONS="-c orgmetra.tenant_record_id=${tenant}" command psql "$@"
}

expect_failure() {
  local label="$1"
  local needle="$2"
  local sql="$3"
  local output status
  set +e
  output="$({ with_tenant "${TENANT_ID}" "${DATABASE_URL}" -v ON_ERROR_STOP=1 -c "${sql}"; } 2>&1)"
  status=$?
  set -e
  if [[ ${status} -eq 0 || "${output}" != *"${needle}"* ]]; then
    echo "${label}: ${output}" >&2
    exit 1
  fi
}

# Build exact parent-compatible canonical JSON fixtures. The payload keys and fixed
# governance values mirror EmploymentWorkCapacityReviewPacket; SQL receives the
# exact UTF-8 bytes plus their SHA-256 rather than a reserialized approximation.
eval "$(python - <<PY
import hashlib, json, shlex
common = {
    "capacity_policy_evidence_digest": "${POLICY_DIGEST}",
    "decision_authority": "not_authorized_to_change_employment_or_compensation",
    "employment_record_reference": "employment_record:${EMPLOYMENT_ID}",
    "employment_terms_evidence_digest": "${TERMS_DIGEST}",
    "evidence_version": 1,
    "human_review_required": True,
    "next_action": "Within tenant_record_id, re-resolve the authoritative Employment and current work-capacity truth at effective_on, verify reviewer identity/authority and the exact reviewed employment-terms and capacity-policy evidence, recalculate Assignment allocation and compensation/payroll impacts, then persist any approved bitemporal capacity change with immutable audit/outbox evidence. This packet does not itself mutate Employment, Assignment, compensation, payroll, leave, or scheduling.",
    "purpose_code": "employment_work_capacity_review",
    "requester_actor_reference": "${REQUESTER}",
    "review_state": "reviewed_for_authoritative_resolution",
    "reviewed_at": "2026-08-26T10:00:00Z",
    "reviewer_actor_reference": "${REVIEWER}",
    "reviewer_identity_evidence_digest": "${REVIEWER_DIGEST}",
    "tenant_record_id": "${TENANT_ID}",
}
fixtures = {
    "REVIEW1": common | {
        "current_capacity_ratio": "0.8000",
        "proposed_capacity_ratio": "1.0000",
        "effective_on": "2026-09-01",
        "reason_code": "employee_agreed_change",
        "recorded_at": "2026-08-26T10:00:01Z",
    },
    "REVIEW2": common | {
        "current_capacity_ratio": "1.0000",
        "proposed_capacity_ratio": "0.6000",
        "effective_on": "2026-10-01",
        "reason_code": "contractual_hours_change",
        "recorded_at": "2026-08-26T10:00:02Z",
    },
    "REVIEW_BAD_CURRENT": common | {
        "current_capacity_ratio": "0.5000",
        "proposed_capacity_ratio": "0.7000",
        "effective_on": "2026-11-01",
        "reason_code": "business_schedule_change",
        "recorded_at": "2026-08-26T10:00:03Z",
    },
    "REVIEW_BAD_GOVERNANCE": common | {
        "current_capacity_ratio": "0.6000",
        "proposed_capacity_ratio": "0.7000",
        "effective_on": "2026-11-01",
        "next_action": "apply now",
        "reason_code": "business_schedule_change",
        "recorded_at": "2026-08-26T10:00:04Z",
    },
}
for name, payload in fixtures.items():
    raw = json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
    print(f"{name}_JSON_SQL={shlex.quote(raw.replace(chr(39), chr(39) * 2))}")
    print(f"{name}_DIGEST={hashlib.sha256(raw.encode('utf-8')).hexdigest()}")
PY
)"

with_tenant "${TENANT_ID}" "${DATABASE_URL}" -v ON_ERROR_STOP=1 <<SQL
INSERT INTO tenant_record (tenant_record_id, tenant_reference)
VALUES ('${TENANT_ID}', 'tenant_alpha'), ('${OTHER_TENANT_ID}', 'tenant_beta');
INSERT INTO person_record (tenant_record_id, person_record_id)
VALUES ('${TENANT_ID}', '${PERSON_ID}');
INSERT INTO employment_record (tenant_record_id, employment_record_id, person_record_id)
VALUES ('${TENANT_ID}', '${EMPLOYMENT_ID}', '${PERSON_ID}');
INSERT INTO employment_record_version (
  tenant_record_id, employment_record_version_id, employment_record_id,
  employment_status_code, effective_from, effective_to
) VALUES (
  '${TENANT_ID}', '${EMPLOYMENT_VERSION_ID}', '${EMPLOYMENT_ID}',
  'active', DATE '2026-01-01', DATE '2027-01-01'
);
SQL

# First application bootstraps authoritative capacity truth only from the reviewed
# employment-terms/capacity-policy evidence; it does not invent prior history.
with_tenant "${TENANT_ID}" "${DATABASE_URL}" -v ON_ERROR_STOP=1 <<SQL
SELECT apply_employment_work_capacity_change(
  '${TENANT_ID}'::uuid,
  '${CAPACITY_RECORD_ID}'::uuid,
  '${CAPACITY_VERSION_1}'::uuid,
  '${EMPLOYMENT_ID}'::uuid,
  '${REVIEW1_JSON_SQL}',
  '${REVIEW1_DIGEST}',
  '${REVIEW_AUDIT}',
  '${REVIEW_AUDIT_DIGEST}',
  '${APPLIER}',
  '${APPLICATION_AUDIT_1}',
  '${APPLICATION_OUTBOX_1}',
  '${APPLICATION_DIGEST_1}'
);
SQL

first_state="$(with_tenant "${TENANT_ID}" "${DATABASE_URL}" -Atqc "
SELECT capacity_ratio::text || '|' || current_capacity_ratio::text || '|' ||
       prior_capacity_match_state || '|' || application_purpose_code || '|' || decision_authority_state
FROM employment_work_capacity_version
WHERE employment_work_capacity_version_id='${CAPACITY_VERSION_1}'::uuid;
")"
if [[ "${first_state}" != "1.0000|0.8000|bootstrap_from_reviewed_terms|employment_work_capacity_change|human_reviewed_authoritative_hris_truth" ]]; then
  echo "first capacity truth persisted unsafe or incomplete state: ${first_state}" >&2
  exit 1
fi

before_first="$(with_tenant "${TENANT_ID}" "${DATABASE_URL}" -Atqc "
SELECT COALESCE(resolve_employment_work_capacity(
  '${TENANT_ID}'::uuid, '${EMPLOYMENT_ID}'::uuid, DATE '2026-08-31', pg_catalog.transaction_timestamp()
)::text, 'none');")"
if [[ "${before_first}" != "none" ]]; then
  echo "capacity resolver invented pre-bootstrap history: ${before_first}" >&2
  exit 1
fi

at_first="$(with_tenant "${TENANT_ID}" "${DATABASE_URL}" -Atqc "
SELECT resolve_employment_work_capacity(
  '${TENANT_ID}'::uuid, '${EMPLOYMENT_ID}'::uuid, DATE '2026-09-01', pg_catalog.transaction_timestamp()
)::text;")"
if [[ "${at_first}" != "1.0000" ]]; then
  echo "capacity resolver missed first authoritative state: ${at_first}" >&2
  exit 1
fi

# A later change must match the already-authoritative current capacity before it
# can append a new effective point.
with_tenant "${TENANT_ID}" "${DATABASE_URL}" -v ON_ERROR_STOP=1 <<SQL
SELECT apply_employment_work_capacity_change(
  '${TENANT_ID}'::uuid,
  '${CAPACITY_RECORD_ID}'::uuid,
  '${CAPACITY_VERSION_2}'::uuid,
  '${EMPLOYMENT_ID}'::uuid,
  '${REVIEW2_JSON_SQL}',
  '${REVIEW2_DIGEST}',
  '${REVIEW_AUDIT}',
  '${REVIEW_AUDIT_DIGEST}',
  '${APPLIER}',
  '${APPLICATION_AUDIT_2}',
  '${APPLICATION_OUTBOX_2}',
  '${APPLICATION_DIGEST_2}'
);
SQL

second_state="$(with_tenant "${TENANT_ID}" "${DATABASE_URL}" -Atqc "
SELECT capacity_ratio::text || '|' || current_capacity_ratio::text || '|' || prior_capacity_match_state
FROM employment_work_capacity_version
WHERE employment_work_capacity_version_id='${CAPACITY_VERSION_2}'::uuid;
")"
if [[ "${second_state}" != "0.6000|1.0000|matched_authoritative_capacity" ]]; then
  echo "later capacity truth did not bind prior authoritative state: ${second_state}" >&2
  exit 1
fi

sep_state="$(with_tenant "${TENANT_ID}" "${DATABASE_URL}" -Atqc "
SELECT resolve_employment_work_capacity(
  '${TENANT_ID}'::uuid, '${EMPLOYMENT_ID}'::uuid, DATE '2026-09-30', pg_catalog.transaction_timestamp()
)::text;")"
oct_state="$(with_tenant "${TENANT_ID}" "${DATABASE_URL}" -Atqc "
SELECT resolve_employment_work_capacity(
  '${TENANT_ID}'::uuid, '${EMPLOYMENT_ID}'::uuid, DATE '2026-10-01', pg_catalog.transaction_timestamp()
)::text;")"
if [[ "${sep_state}" != "1.0000" || "${oct_state}" != "0.6000" ]]; then
  echo "effective-point capacity resolution is wrong: Sep=${sep_state}, Oct=${oct_state}" >&2
  exit 1
fi

expect_failure \
  "capacity change accepted forged review next action" \
  "review governance state is unsupported or noncanonical" \
  "SELECT apply_employment_work_capacity_change(
     '${TENANT_ID}'::uuid,
     '${CAPACITY_RECORD_ID}'::uuid,
     '${CAPACITY_VERSION_BAD}'::uuid,
     '${EMPLOYMENT_ID}'::uuid,
     '${REVIEW_BAD_GOVERNANCE_JSON_SQL}',
     '${REVIEW_BAD_GOVERNANCE_DIGEST}',
     '${REVIEW_AUDIT}',
     '${REVIEW_AUDIT_DIGEST}',
     '${APPLIER}',
     'audit_event:00000000-0000-4000-8000-000000000054',
     'outbox_event:00000000-0000-4000-8000-000000000063',
     '1111111111111111111111111111111111111111111111111111111111111111'
   );"

expect_failure \
  "capacity change ignored authoritative current capacity" \
  "reviewed current capacity does not match authoritative capacity" \
  "SELECT apply_employment_work_capacity_change(
     '${TENANT_ID}'::uuid,
     '${CAPACITY_RECORD_ID}'::uuid,
     '${CAPACITY_VERSION_BAD}'::uuid,
     '${EMPLOYMENT_ID}'::uuid,
     '${REVIEW_BAD_CURRENT_JSON_SQL}',
     '${REVIEW_BAD_CURRENT_DIGEST}',
     '${REVIEW_AUDIT}',
     '${REVIEW_AUDIT_DIGEST}',
     '${APPLIER}',
     'audit_event:00000000-0000-4000-8000-000000000054',
     'outbox_event:00000000-0000-4000-8000-000000000063',
     '1111111111111111111111111111111111111111111111111111111111111111'
   );"

expect_failure \
  "capacity change accepted forged review digest" \
  "review evidence digest does not match exact JSON bytes" \
  "SELECT apply_employment_work_capacity_change(
     '${TENANT_ID}'::uuid,
     '${CAPACITY_RECORD_ID}'::uuid,
     '${CAPACITY_VERSION_BAD}'::uuid,
     '${EMPLOYMENT_ID}'::uuid,
     '${REVIEW_BAD_CURRENT_JSON_SQL}',
     '2222222222222222222222222222222222222222222222222222222222222222',
     '${REVIEW_AUDIT}',
     '${REVIEW_AUDIT_DIGEST}',
     '${APPLIER}',
     'audit_event:00000000-0000-4000-8000-000000000054',
     'outbox_event:00000000-0000-4000-8000-000000000063',
     '1111111111111111111111111111111111111111111111111111111111111111'
   );"

expect_failure \
  "reviewer could apply their own work-capacity review" \
  "applier must differ from requester and reviewer" \
  "SELECT apply_employment_work_capacity_change(
     '${TENANT_ID}'::uuid,
     '${CAPACITY_RECORD_ID}'::uuid,
     '${CAPACITY_VERSION_BAD}'::uuid,
     '${EMPLOYMENT_ID}'::uuid,
     '${REVIEW_BAD_CURRENT_JSON_SQL}',
     '${REVIEW_BAD_CURRENT_DIGEST}',
     '${REVIEW_AUDIT}',
     '${REVIEW_AUDIT_DIGEST}',
     '${REVIEWER}',
     'audit_event:00000000-0000-4000-8000-000000000054',
     'outbox_event:00000000-0000-4000-8000-000000000063',
     '1111111111111111111111111111111111111111111111111111111111111111'
   );"

expect_failure \
  "cross-tenant application accepted parent review evidence" \
  "tenant context does not match requested tenant" \
  "SELECT apply_employment_work_capacity_change(
     '${OTHER_TENANT_ID}'::uuid,
     '20000000-0000-7000-8000-000000000031'::uuid,
     '20000000-0000-7000-8000-000000000032'::uuid,
     '${EMPLOYMENT_ID}'::uuid,
     '${REVIEW1_JSON_SQL}',
     '${REVIEW1_DIGEST}',
     '${REVIEW_AUDIT}',
     '${REVIEW_AUDIT_DIGEST}',
     '${APPLIER}',
     'audit_event:00000000-0000-4000-8000-000000000054',
     'outbox_event:00000000-0000-4000-8000-000000000063',
     '1111111111111111111111111111111111111111111111111111111111111111'
   );"

expect_failure \
  "capacity history was rewriteable" \
  "immutable" \
  "UPDATE employment_work_capacity_version
   SET capacity_ratio = 0.9000
   WHERE employment_work_capacity_version_id='${CAPACITY_VERSION_1}'::uuid;"
expect_failure \
  "capacity history was deletable" \
  "immutable" \
  "DELETE FROM employment_work_capacity_version
   WHERE employment_work_capacity_version_id='${CAPACITY_VERSION_1}'::uuid;"
expect_failure \
  "capacity history could be truncated" \
  "cannot be truncated" \
  "TRUNCATE employment_work_capacity_version CASCADE;"

for forbidden_column in medical_detail disability_detail diagnosis_text free_form_note compensation_value payroll_value rating_value candidate_reference; do
  count="$(psql "${DATABASE_URL}" -Atqc "
    SELECT count(*) FROM information_schema.columns
    WHERE table_schema='public'
      AND table_name IN ('employment_work_capacity_record','employment_work_capacity_version')
      AND column_name='${forbidden_column}';")"
  if [[ "${count}" != "0" ]]; then
    echo "work-capacity persistence introduced prohibited sensitive column: ${forbidden_column}" >&2
    exit 1
  fi
done

rls_state="$(psql "${DATABASE_URL}" -Atqc "
SELECT string_agg(relname || ':' || relrowsecurity::text || ':' || relforcerowsecurity::text, ',' ORDER BY relname)
FROM pg_class
WHERE relname IN ('employment_work_capacity_record','employment_work_capacity_version');")"
if [[ "${rls_state}" != "employment_work_capacity_record:true:true,employment_work_capacity_version:true:true" ]]; then
  echo "work-capacity RLS is not enabled and forced: ${rls_state}" >&2
  exit 1
fi

public_execute="$(psql "${DATABASE_URL}" -Atqc "
SELECT has_function_privilege(
  'public',
  'apply_employment_work_capacity_change(uuid,uuid,uuid,uuid,text,text,text,text,text,text,text,text)',
  'EXECUTE'
);")"
if [[ "${public_execute}" != "f" ]]; then
  echo "authoritative work-capacity mutation function is executable by PUBLIC" >&2
  exit 1
fi

psql "${DATABASE_URL}" -v ON_ERROR_STOP=1 <<'SQL'
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='capacity_reader') THEN
    CREATE ROLE capacity_reader NOSUPERUSER NOBYPASSRLS;
  END IF;
END $$;
GRANT SELECT ON employment_work_capacity_record, employment_work_capacity_version TO capacity_reader;
SQL

visible="$(psql "${DATABASE_URL}" -Atqc "
BEGIN;
SET LOCAL ROLE capacity_reader;
SET LOCAL orgmetra.tenant_record_id='${TENANT_ID}';
SELECT count(*) FROM employment_work_capacity_version;
COMMIT;" | tail -n 1)"
if [[ "${visible}" != "2" ]]; then
  echo "tenant reader could not see own capacity history: ${visible}" >&2
  exit 1
fi

hidden="$(psql "${DATABASE_URL}" -Atqc "
BEGIN;
SET LOCAL ROLE capacity_reader;
SET LOCAL orgmetra.tenant_record_id='${OTHER_TENANT_ID}';
SELECT count(*) FROM employment_work_capacity_version;
COMMIT;" | tail -n 1)"
if [[ "${hidden}" != "0" ]]; then
  echo "foreign tenant could see capacity history: ${hidden}" >&2
  exit 1
fi

printf '%s\n' "Employment work-capacity persistence: PASS"
